spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener
spring.datasource.username=root
spring.datasource.password=Avnish@123kr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect